### ISSUE TITLE
ConcurrentModificationException crash

### ISSUE THREAD

**Issue by ishaangarg** [mocklets/pluto#188]
Encountered a crash while switching between app & pluto multiple times.

**Smartphone:**
 - Device: Redmi 6A
 - OS: Android 9
 - Library Version: 2.0.5

**Stacktrace**
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.pluto.plugins.logger.internal.ui.ListFragment.filteredLogs(ListFragment.kt:147)
       at com.pluto.plugins.logger.internal.ui.ListFragment.logsObserver$lambda-4(ListFragment.kt:102)
       at com.pluto.plugins.logger.internal.ui.ListFragment.$r8$lambda$IYREEwJE8MLnfconFlbEOxipqio(ListFragment.kt)
       at com.pluto.plugins.logger.internal.ui.ListFragment$$InternalSyntheticLambda$1$1b2501221c71d499c404830ca2439bf594826a99001a482297c2784bbc3ac50d$0.onChanged(ListFragment.java:4)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6820)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
```

**Comment by ishaangarg** [comment]
Hey Prateek,
this is leading to a lot of crashes. Is there a plan to release the fix soon?

**Comment by srtvprateek** [comment]
vesion `2.0.8` is live
