### ISSUE TITLE
Timber crash due to lambda fun in java

### ISSUE THREAD

**Issue by ishaangarg** [mocklets/pluto#192]
**Describe the bug**
App crashes when trying to log to Timber with a pluto tree from a lambda fun in a java class

**To Reproduce**
1. Add a lambda fun in a java class
2. log to timber in the lambda fun, like so: `Timber.d("this will crash");`
3. run the app to reach this log & we'll get a crash

**Smartphone:**
 - Device: Emulator
 - OS: Android 12
 - Library Version: 2.0.5

**Stacktrace**
```
FATAL EXCEPTION: main
                 java.lang.NullPointerException: it.fileName must not be null
                 	at com.pluto.plugins.logger.internal.LogsProcessor$Companion.stackTraceElement(LogsProcessor.kt:32)
                 	at com.pluto.plugins.logger.PlutoTimberTree.getStackTraceElement(PlutoTimberTree.kt:63)
                 	at com.pluto.plugins.logger.PlutoTimberTree.log(PlutoTimberTree.kt:19)
                 	at timber.log.Timber$Tree.prepareLog(Timber.kt:168)
                 	at timber.log.Timber$Tree.d(Timber.kt:51)
                 	at timber.log.Timber$Forest.d(Timber.kt:292)
                 	at timber.log.Timber.d(Unknown Source:2)
                 	at in.shadowfax.gandalf.utils.services.MqttService.lambda$new$0$in-shadowfax-gandalf-utils-services-MqttService(MqttService.java:282)
                 	at in.shadowfax.gandalf.utils.services.MqttService$$ExternalSyntheticLambda0.onChanged(Unknown Source:4)
                 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)```

**Comment by srtvprateek** [comment]
@ishaangarg can you share the code snippet also?

**Comment by ishaangarg** [comment]
Sorry should've started with the snippet. here it is:

`btn.setOnClickListener(v -> Timber.d("this will crash"));`

For reference, here's how Pluto is initialized:
```
private void initPluto() {
        new Pluto.Installer(this)
                .addPlugin(new PlutoNetworkPlugin("network"))
                .addPlugin(new PlutoExceptionsPlugin("exceptions"))
                .addPlugin(new PlutoLoggerPlugin("logger"))
                .addPlugin(new PlutoSharePreferencesPlugin("sharedPref"))
                .addPlugin(new PlutoRoomsDatabasePlugin("rooms-db"))
                .install();
        PlutoRoomsDBWatcher.INSTANCE.watch("my-db", RoomDb.class);
        Timber.plant(new PlutoTimberTree());
}
```
