### ISSUE TITLE
Crashes detected and show only white page, caused by divider

### ISSUE THREAD

**Issue by JosephSanjaya** [mocklets/pluto#198]
**Describe the bug**
Crashes happens when we access datastore preferences menu, it only showing white pages. Does it had relation with material3 implementation?

**To Reproduce**
1. Implement Material3, and pluto
2. Click on DataStore Preferences menu
3. Crash occured and showing blank pages

**Expected behavior**
It should shown the datastore debug menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/48875981/208020735-4afcd319-fee9-4d41-8e5a-ca13be688b2a.png)

**Smartphone (please complete the following information):**
 - Device: Emulator and Windows Subsystem
 - OS: Android 13
 - Browser: Chrome
 - Library Version: 2.0.6

**Additional context**
Stack trace
```
EXCEPTION : 
java.lang.NoSuchMethodError: No static method Divider-oMI9zvI(Landroidx/compose/ui/Modifier;JFFLandroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material3/DividerKt; or its super classes (declaration of 'androidx.compose.material3.DividerKt' appears in /data/app/~~WT1lt4pFbbsxQ0RLe_6jSQ==/com.awantunai.app-DWvJmNn8NEttl4xm6R_veQ==/base.apk)
	 at com.pluto.plugins.datastore.pref.internal.compose.MainComposableKt.MainComposable(MainComposable.kt:54)
	 at com.pluto.plugins.datastore.pref.internal.BaseFragment$onCreateView$1$1$1.invoke(BaseFragment.kt:46)
	 at com.pluto.plugins.datastore.pref.internal.BaseFragment$onCreateView$1$1$1.invoke(BaseFragment.kt:38)
	 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	 at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	 at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
	 at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2666)
	 at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:250)
	 at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:249)
	 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	 at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	 at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
	 at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
	 at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
	 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	 at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	 at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
	 at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$4.invoke(null:8)
	 at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$4.invoke(null:10)
	 at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	 at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
	 at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2643)
	 + 27 more lines



==================

Thread : MAIN (id : 2,  priority : Normal,  is_Daemon : false,  state : RUNNABLE)

==================

APP STATE : 
App Version : 4.17.2-alpha (216)
Android  (OS : 12, API_Level : 32)
Orientation : landscape
is_Rooted : false

==================

DEVICE INFO : 
Model : Windows Subsystem for Android(TM)
Screen : { height : 1080px, width : 1920px, density :  160, size :  14.0 inches }

-------------------------------------
report generated by Pluto (https://plutolib.com)
```

**Comment by srtvprateek** [comment]
hey @JosephSanjaya,
can you share the code snippet on how you are integrating the plugin.

**Comment by rishabh-cred** [comment]
The divider used is from material3 package. Can you share the material package your app is using?
