### ISSUE TITLE
UninitializedPropertyAccessException - logDao 

### ISSUE THREAD

**Issue by Woren** [mocklets/pluto#245]
During running a unit tests I got exception below. Sorry, don't have exact reproducer.
Version 2.1.0 and 2.1.3 is fine but version 2.1.4 is throwing exception.

Gradle 8.0.2, AGP 8.0.2, Kotlin 1.8.20

Exception in thread "DefaultDispatcher-worker-5 @coroutine#106" kotlin.UninitializedPropertyAccessException: lateinit property logDao has not been initialized
	at com.pluto.plugins.logger.internal.persistence.LogDBHandler$persist$1.invokeSuspend(LogDBHandler.kt:25)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineId(106), "coroutine#106":StandaloneCoroutine{Cancelling}@623ff3c8, Dispatchers.IO]

**Comment by srtvprateek** [comment]
seems like a case when `log` request came before Pluto plugin is initialised.
we just enabled feature to persist logs across sessions #235 which needs plugin to be initialised.

will check this.
