### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot serialize Kotlin type

### ISSUE THREAD

**Issue by Drabu** [mocklets/pluto#254]
Works well in 2.0.9 but breaking on the updated lib version. 

EXCEPTION : 
java.lang.IllegalArgumentException: Cannot serialize Kotlin type in.shadowfax.gandalf.features.common.payout.models.RiderDocument. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
     at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:98)
     at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
     at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
     at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.toJson(StandardJsonAdapters.java:374)
     at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
     at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:61)
     at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:30)
     at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
     at com.pluto.plugins.logger.internal.LogDataJsonAdapter.toJson(LogDataJsonAdapter.kt:150)
     at com.pluto.plugins.logger.internal.LogDataJsonAdapter.toJson(LogDataJsonAdapter.kt:27)
     at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
     at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)
     at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:90)
     at com.pluto.plugins.logger.internal.persistence.EntityConverters.logToString(EntityConverters.kt:21)
     at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$1.bind(LogDao_Impl.java:56)
     at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$1.bind(LogDao_Impl.java:42)
     at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:51)
     at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$4.call(LogDao_Impl.java:87)
     at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$4.call(LogDao_Impl.java:82)
     at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
     at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
     at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(TransactionExecutor.kt:0)
     at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
     + 3 more lines

**Comment by srtvprateek** [comment]
can you send the code snippet causing this issue?

**Comment by Sushruth17** [comment]
Similar crash in latest version 
works only till 2.0.9

```
Fatal Exception: java.lang.IllegalArgumentException: Platform class java.net.InetSocketAddress requires explicit JsonAdapter to be registered
       at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:76)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
       at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.toJson(StandardJsonAdapters.java:374)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
       at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:61)
       at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:30)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
       at com.pluto.plugins.logger.internal.LogDataJsonAdapter.toJson(LogDataJsonAdapter.kt:150)
       at com.pluto.plugins.logger.internal.LogDataJsonAdapter.toJson(LogDataJsonAdapter.kt:27)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
       at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)
       at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:90)
       at com.pluto.plugins.logger.internal.persistence.EntityConverters.logToString(EntityConverters.kt:21)
       at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$1.bind(LogDao_Impl.java:62)
       at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$1.bind(LogDao_Impl.java:43)
       at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:50)
       at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$4.call(LogDao_Impl.java:93)
       at com.pluto.plugins.logger.internal.persistence.LogDao_Impl$4.call(LogDao_Impl.java:88)
       at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:64)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
       at androidx.room.TransactionExecutor.$r8$lambda$FZWr2PGmP3sgXLCiri-DCcePXSs()
       at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Sushruth17** [comment]
Hey @srtvprateek , had got similar crash

issue was fixed by adding .toString to the value of the map being logged 

val map = HashMap<String, Any>
val someObject = SomeObject()
map["someObject"] = someObject.toString()

if .toString() is removed it crashes above version 2.0.9
