### ISSUE TITLE
Endless response on random api requests

### ISSUE THREAD

**Issue by pavelperc** [mocklets/pluto#329]
**Describe the bug**
Sometimes api requests continue endlessly, but the real request succedded.
Unlike this issue: https://github.com/androidPluto/pluto/issues/314, it happens on all requests, even with non-empty body.

Also found this in logs:
```
java.io.IOException: An error occurred while creating a Pluto file
19:29:52.493 System.err                           W  	at com.pluto.plugin.libinterface.FilesInterface.createFile(FilesInterface.kt:23)
19:29:52.493 System.err                           W  	at com.pluto.plugin.libinterface.FilesInterface.createFile$default(FilesInterface.kt:12)
19:29:52.493 System.err                           W  Caused by: java.io.IOException: File /data/user/0/com.sampleapp/files/pluto-0 already exists
19:29:52.493 System.err                           W  	at com.pluto.plugin.libinterface.FilesInterface.createFile(FilesInterface.kt:19)
```

The problem cause is here:
https://github.com/androidPluto/pluto/blob/develop/pluto-plugins/plugins/network/interceptor-okhttp/lib/src/main/kotlin/com/pluto/plugins/network/okhttp/internal/ResponseReportingSinkCallback.kt#L19
file is null and onComplete never calls.

**To Reproduce**
1. Quickly run any successful request 100 times
2. open "network calls" plugin
3. Some api calls are in endless loading

**Expected behavior**
All requests are completed.

**Screenshots**
<img width="358" alt="Screenshot 2024-11-07 at 19 37 36" src="https://github.com/user-attachments/assets/09766566-3b9a-4c9e-a86e-15b9c27d0afa">

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: android 14
 - Library Version 2.2.2

**Comment by pavelperc** [comment]
One more error:
```
19:54:47.275 System.err                           W  java.io.IOException: Response payload couldn't be processed by Pluto
19:54:47.275 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.ResponseReportingSinkCallback.readResponseBuffer(ResponseReportingSinkCallback.kt:41)
19:54:47.275 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.ResponseReportingSinkCallback.onSuccess(ResponseReportingSinkCallback.kt:21)
19:54:47.275 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.utilities.ReportingSink.close(ReportingSink.kt:70)
19:54:47.275 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.utilities.TeeSource.safeCloseSideStream(TeeSource.kt:56)
19:54:47.275 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.utilities.TeeSource.read(TeeSource.kt:28)
19:54:47.275 System.err                           W  	at okio.ForwardingSource.read(ForwardingSource.kt:27)
19:54:47.275 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.utilities.DepletingSource.read(DepletingSource.kt:18)
19:54:47.275 System.err                           W  	at okio.RealBufferedSource.read(RealBufferedSource.kt:192)
19:54:47.275 System.err                           W  	at okio.ForwardingSource.read(ForwardingSource.kt:27)
19:54:47.275 System.err                           W  	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
19:54:47.275 System.err                           W  	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:161)
19:54:47.275 System.err                           W  	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
19:54:47.275 System.err                           W  	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
19:54:47.275 System.err                           W  	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
19:54:47.275 System.err                           W  	at java.io.InputStreamReader.read(InputStreamReader.java:180)
19:54:47.276 System.err                           W  Caused by: java.io.FileNotFoundException: /data/user/0/ru.plus.xxx.debug/files/pluto-0: open failed: ENOENT (No such file or directory)
19:54:47.276 System.err                           W  	at libcore.io.IoBridge.open(IoBridge.java:574)
19:54:47.276 System.err                           W  	at java.io.FileInputStream.<init>(FileInputStream.java:160)
19:54:47.276 System.err                           W  	at okio.Okio__JvmOkioKt.source(JvmOkio.kt:181)
19:54:47.276 System.err                           W  	at okio.Okio.source(Unknown Source:1)
19:54:47.276 System.err                           W  	at com.pluto.plugins.network.okhttp.internal.ResponseReportingSinkCallback.readResponseBuffer(ResponseReportingSinkCallback.kt:33)
19:54:47.276 System.err                           W  	... 55 more
19:54:47.276 System.err                           W  Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
19:54:47.276 System.err                           W  	at libcore.io.Linux.open(Native Method)
19:54:47.276 System.err                           W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
19:54:47.276 System.err                           W  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
19:54:47.276 System.err                           W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
19:54:47.276 System.err                           W  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7758)
19:54:47.276 System.err                           W  	at libcore.io.IoBridge.open(IoBridge.java:560)
19:54:47.276 System.err                           W  	... 59 more
```

**Comment by pavelperc** [comment]
Possible problem cause is that FileInterface is not a singleton, and FileInterface.uniqueIdGenerator is recreated every time:
https://github.com/androidPluto/pluto/blob/develop/pluto-plugins/base/lib/src/main/java/com/pluto/plugin/libinterface/PlutoInterface.kt#L31
