### ISSUE TITLE
java.lang.VerifyError on API 19

### ISSUE THREAD

**Issue by AlexanderShirokih** [mocklets/pluto#76]
**Describe the bug**
In development branch minSdkVersion is 19, but Pluto crashes the application when Pluto.initialize(context) is called. Any older versions(tested with 0.23, 1.0.0, 1.0.2-beta, 1.0.4) that has minSdkVersion < 21 also causes this bug.

```
Process: com.sampleapp, PID: 6020
    java.lang.VerifyError: com/mocklets/pluto/modules/activities/ActivityTracker$lifecycleCallbacks$1
        at com.mocklets.pluto.modules.activities.ActivityTracker.<init>(ActivityTracker.kt:67)
        at com.mocklets.pluto.Pluto.initialize(Pluto.kt:37)
        at com.sampleapp.SampleApp.onCreate(SampleApp.kt:14)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

**To Reproduce**
1. Set minSdkVersion in sample project to 19
2. Run the application

**Expected behavior**
Pluto successfully works on API 19

**Smartphone:**
-  Android emulator API 19

**Comment by srtvprateek** [comment]
@AlexanderShirokih tried to reproduce the issue after setting `minSdkVersion 19`,  but not getting the above exception.
Can you share the configuration of the emulator?

**Comment by AlexanderShirokih** [comment]
@srtvprateek, config.ini:

Name: Nexus_5_API_19

CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/alexander/.android/avd/Nexus_5_API_19.avd
Target: google_apis [Google APIs] (API level 19)
Skin: nexus_5
SD Card: 512 MB
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 19
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Nexus 5 API 19
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1920
vm.heapSize: 128
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-19/google_apis/x86/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Nexus_5_API_19
hw.lcd.density: 480
hw.arc: false
hw.device.hash2: MD5:041eb4f348dec9fd18091e32004fae73
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 1600M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
