### ISSUE TITLE
App crashes with java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by AlexanderShirokih** [mocklets/pluto#84]
**Describe the bug**
A fantom bug reproduced  in 1.0.4 that causes a crash with ConcurrentModificationException. 

**To Reproduce**
Causes randomly.

**Expected behavior**
Application doesn't crashes

**Stack trace**
```
java.util.ConcurrentModificationException: null
	 at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
	 at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
	 at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	 at java.util.Collections$SynchronizedCollection.toArray(Collections.java:2075)
	 at java.util.ArrayList.<init>(ArrayList.java:191)
	 at com.mocklets.pluto.modules.network.NetworkCallsRepo.updateLiveData(NetworkCallsRepo.kt:27)
	 at com.mocklets.pluto.modules.network.NetworkCallsRepo.set(NetworkCallsRepo.kt:16)
	 at com.mocklets.pluto.PlutoInterceptor.intercept(PlutoInterceptor.kt:43)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	 at zerobranch.androidremotedebugger.logging.NetLoggingInterceptor.intercept(NetLoggingInterceptor.java:147)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
	 + 4 more linesThread : OKHTTP DISPATCHER (id : 11078,  priority : Normal,  is_Daemon : false,  state : RUNNABLE)==================APP STATE : 
App Version : 1.61.0 (16100)
Android  (OS : 10, API_Level : 29)
Orientation : portrait
is_Rooted : false==================DEVICE INFO : 
Model : Samsung SM-A515F
Screen : { height : 2186px, width : 2186px, density :  420 dpi, size :  6.0 inches }-----
report powered by Pluto https://pluto.mocklets.com
```

**Comment by AlexanderShirokih** [comment]
@srtvprateek, @mocklets-tech, Fix that was made in #85 is not working.
Can you apply the solution in https://github.com/mocklets/pluto/pull/85#issuecomment-926647272? (Tested, it works)
Alternatively you can try to replace SyncronizedMap with ConcurrentHashMap.
