### ISSUE TITLE
Pluto is crashing when clicking on notification after app has been killed.

### ISSUE THREAD

**Issue by mlilienberg** [mocklets/pluto#93]
**Describe the bug**
Pluto app is crashing with `lateinit property session has not been initialized` when clicking on notification after the target app crashed or has been killed. I did not try to reproduce it in a more simple app with different launch mode.

**To Reproduce**
1. Kill the hosting app
2. Click on the notification: "Pluto is debugging ..."
3. See app is crashing 

**Expected behavior**
Pluto notification is dismissed after app is killed/crashed. Alternatively if notification can not be dismissed for technical reasons to show an error message that Pluto session has ended. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Emulator android 10, Pixel 5 android 12
 - OS: Android 10, Android 12
 - Library Version 1.1.0

**Additional context**
-

**Comment by srtvprateek** [comment]
hey @mlilienberg, can you please share the stack trace for the crash

**Comment by mlilienberg** [comment]
I tried to reproduce a crash with a simple example app but without success. In a simple setup Pluto is starting correctly. Our app has multiple 100.000 lines of code in many modules and integrating a lot of third party dependencies, so i can not exclude that our setup is causing this. This is the stacktrace that i get in my app.

```
2021-10-05 16:06:19.015 7877-7877/com.example.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app.debug, PID: 7877
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app.debug/com.mocklets.pluto.ui.PlutoActivity}: android.view.InflateException: Binary XML file line #12 in com.example.app.debug:layout/pluto___activity_pluto: Binary XML file line #12 in com.example.app.debug:layout/pluto___activity_pluto: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3639)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3796)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.view.InflateException: Binary XML file line #12 in com.example.app.debug:layout/pluto___activity_pluto: Binary XML file line #12 in com.example.app.debug:layout/pluto___activity_pluto: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #12 in com.example.app.debug:layout/pluto___activity_pluto: Error inflating class fragment
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property session has not been initialized
        at com.mocklets.pluto.Pluto.getSession$pluto_release(Pluto.kt:22)
        at com.mocklets.pluto.ui.BaseFragment.setupPager(BaseFragment.kt:41)
        at com.mocklets.pluto.ui.BaseFragment.onViewCreated(BaseFragment.kt:31)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:392)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:281)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:140)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:319)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:298)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:461)
        at android.app.Activity.setContentView(Activity.java:3520)
        at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:403)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:326)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
        at com.mocklets.pluto.ui.PlutoActivity.onCreate(PlutoActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3612)
2021-10-05 16:06:19.016 7877-7877/com.example.app.debug E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3796)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by srtvprateek** [comment]
thanks, i ll check this

**Comment by mlilienberg** [comment]
I was debugging the issue a bit and found the cause. In our project we are initializing Pluto inside a koin module definition 
```
single<Interceptor>(named(PLUTO_INTERCEPTOR)) {
        Pluto.initialize(androidApplication())
        PlutoInterceptor()
    }
```
Doing it this way Pluto is crashing when opening Pluto after the inspected app is killed or has crashed. It seems that the Pluto singleton becomes garbage collected when the application is closed. I am not sure why this only happens when it is loaded via koin maybe the object is cleaned also in other situations. On the other hand this way Pluto is leaking the application context.

**Comment by jimlyas** [comment]
I think for this, you should place `Pluto.initialize(androidApplication())` inside your Application class.

So your Koin module only defining the interceptor.
